Modify the Loan entity to allow references to Reservations.
bic-org-uk/bic-lcf pull request #178
Opened 2019-03-29 19:23 UTC by mdovey

Modify the Loan entity to allow references to Reservations as discussed under issue #143

2019-03-29 19:24 UTC, mdovey commented
As this change is backwards compatible, fairly straightforward, and agreed by the Technical Panel, I see no reason not to roll this into 1.1.0

2019-03-29 22:05 UTC, franciscave requested changes
The identifier for this new element should be E05D14, because E05C13 already exists and the number following 'C' (composite) and 'D' (data element) should never be the same within the same entity.

2019-03-29 22:46 UTC, mdovey commented
Ah, I missed that one (I was incrementing the number of the last element!)

2019-03-30 19:14 UTC, franciscave approved these changes

2019-03-30 20:20 UTC, merged