Standardise on Added\Changed in v1.x.x etc.
bic-org-uk/bic-lcf pull request #184
Opened 2019-03-30 21:19 UTC by mdovey

Standardise on Added\Changed in v1.x.x etc.
Change 1.0.2 references to 1.1.0

See issue #180

2019-03-30 21:49 UTC, franciscave requested changes
Can you check the link from Q02C02 in this spec (line 164) to Q02 in the Data Frameworks spec? I think that the link should be to 'LCF-DataFrameworks.md#f02'.

2019-03-30 21:50 UTC, franciscave commented
Otherwise, thank you for doing a great job on updating the added/changed notes!

2019-03-30 22:44 UTC, mdovey commented
OK, should be fixed now.

2019-03-31 08:23 UTC, franciscave approved these changes

2019-03-31 08:34 UTC, merged