Added section on Determining if an Operation requires Authentication
bic-org-uk/bic-lcf pull request #223
Opened 2019-06-13 13:26 UTC by mdovey

To address issue #202

2019-06-13 13:26 UTC, mdovey commented
In updating the documentation, I realised that in addition to a specific document on authentication (originally from the wiki page), there was also some similar information in the REST implementation document as Implementation notes.

I've merged the standalone document into the implementation notes to avoid duplication (also having two places covering the same ground might lead to contradictions between them).

However, the implementation notes (but not the standalone document), also allowed patron authentication via HTTP query parameters - see Implementation Note 2A. Should this be deprecated? It isn't implementable as written as it requests that the password is encrypted but doesn't specify what encryption algorithm to use.

2019-06-14 14:49 UTC, mdovey commented
On reflection, I thought that issue #217 might be addressed in the Implementation Notes, and made additions accordingly

2019-06-18 16:45 UTC, franciscave requested changes
For clarity, please change "200\201" in line 145 to "200 or 201", and "401/403" in line 149 to "401 or 403".

2019-06-30 21:34 UTC, franciscave approved these changes

2019-07-12 11:14 UTC, merged