Minor editorial typos in documentation
bic-org-uk/bic-lcf pull request #307
Opened 2023-11-06 15:38 UTC by franciscave

Tidied up some stylistic inconsistences:
- removed unwanted parentheses around "_Added in v1.3.0_"
- changed '_added_' to '_Added_' in a few instances.

2023-11-07 08:28 UTC, mdovey requested changes
Could you check the edits - it looks like you've deleted the version number in a few cases

2023-11-07 08:28 UTC, mdovey commented on docs/LCF-InformationEntityXMLBindings.md
It looks like in this file you've deleted v1.3.0, and replace with v!?

2023-11-07 10:26 UTC, franciscave commented
Hmm... definitely a slip on my part, but the Github user interface is partly to blame: the 'Delete' button is very close to the 'Find' button in the search dialogue panel. I spotted this happening elsewhere, but obviously missed these two in my haste.

2023-11-08 12:10 UTC, mdovey approved these changes

2023-11-08 12:10 UTC, merged