327 create a method to query which version of lcf an endpoint implements
bic-org-uk/bic-lcf pull request #333
Opened 2024-05-23 16:25 UTC by anthonywhitford

This PR includes all the changes for Issue 327, introducing the new LCF VERSION entity, E16, and removing the /1.0/ from within the REST implementation standard. The new LcfVersion XML entity within the schema does not extend the default LcfEntity, as there is no requirement for an <identifier> as this is a statement of a version, not an entity row in a table of data. 

This is a breaking change - so this should be in LCF 1.4.x rather than a patch for 1.3

2024-05-24 15:10 UTC, franciscave requested changes
Looks OK to me, apart from some possible inconsistencies in changes to LCF version numbers. See comments on individual file changes.

2024-05-24 15:10 UTC, franciscave commented on docs/LCF-DataFrameworks.md
Should "v1.x.x" be "v1.4.x" as you have it on other file changes?

2024-05-24 15:10 UTC, franciscave commented on docs/LCF-RESTWebServiceSpecification.md
Should "v1.4.0" be "v1.4.x" as you have it elsewhere?

2024-05-28 13:19 UTC, anthonywhitford commented on docs/LCF-DataFrameworks.md
Good spot!

2024-05-28 13:19 UTC, anthonywhitford commented on docs/LCF-RESTWebServiceSpecification.md
Good spot!

2024-05-28 13:50 UTC, franciscave approved these changes
Fine now.

2025-01-11 14:36 UTC, merged