Update LCF_ChangeLog.md
bic-org-uk/bic-lcf pull request #337
Opened 2024-06-27 19:59 UTC by anthonywhitford

Updated change log inline with review group meeting from 9th April. #336

2024-06-28 09:00 UTC, franciscave requested changes

2024-06-28 09:00 UTC, franciscave commented on docs/LCF_ChangeLog.md
Requested changes in line 23: deprecated -> deprecate, added -> add. Rationale: to make consistent use of the present tense.

2024-06-28 09:02 UTC, franciscave requested changes

2024-06-28 09:02 UTC, franciscave commented on docs/LCF_ChangeLog.md
Requested change in line 44: affected -> affect. Rationale: consistent use of present tense, as in line 23.

2024-06-28 09:03 UTC, franciscave commented
Apart from the requested changes in two lines, I think this is great.

2024-06-28 14:14 UTC, anthonywhitford commented on docs/LCF_ChangeLog.md
Done

2024-06-28 14:15 UTC, anthonywhitford commented on docs/LCF_ChangeLog.md
Done

2024-06-29 14:34 UTC, franciscave approved these changes
Thanks for making the corrections. I think that, for consistency, there may need to be a blank line added between lines 32 and 33, i.e. above the heading 'Payment modifications'. Other than that, it looks good.

2024-07-06 11:39 UTC, anthonywhitford commented
@franciscave I've added in the blank line on lines 32/33 as requested.

2024-07-06 11:40 UTC, anthonywhitford commented
@mdovey Could you review and (hopefully) approve please? The branch rules require two approvers before a merge is possible.

2024-12-12 09:30 UTC, mdovey approved these changes

2024-12-12 09:30 UTC, merged